# Generated by Django 2.0.2 on 2018-02-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('room_name', models.CharField(help_text='this is the room name', max_length=56, primary_key=True, serialize=False)),
                ('available', models.BooleanField()),
            ],
        ),
    ]
